# Image processing assignment #3

**Student**: Aleksandr J. Smoliakov, MIF Data Science, MSc year 1  
**Date**: 2024-12-12

## FISH Signal Counts

In [ ]:
!python python/main.py fish-signal-counts \
    "data/input/BXY-ABCD_Region 002_FOV 00040_Acridine.tif" \
    "data/input/BXY-ABCD_Region 002_FOV 00040_FITC.tif" \
    "data/input/BXY-ABCD_Region 002_FOV 00040_DAPI.tif"

## Circuit Board Quality Assurance

In [57]:
!python python/main.py circuit-board-qa data/input/pcb-xray.tif

Number of detected regions: 21
/home/aleks/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/aleks/.local/lib/python3.10/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(

Detected soldering regions:

Detected drilled holes:
  Hole 1: Area = 25, Centroid = (11.0, 87.0)
  Hole 2: Area = 25, Centroid = (14.0, 55.0)
  Hole 3: Area = 25, Centroid = (22.0, 116.0)
  Hole 4: Area = 25, Centroid = (23.0, 144.0)
  Hole 5: Area = 25, Centroid = (36.0, 58.0)
  Hole 6: Area = 24, Centroid = (36.875, 86.0)
  Hole 7: Area = 25, Centroid = (49.0, 115.0)
  Hole 8: Area = 25, Centroid = (49.0, 144.0)
  Hole 9: Area = 25, Centroid = (60.0, 58.0)
  Hole 10: Area = 25, Centroid = (60.0, 87.0)
  Hole 11: Area = 52, Centroid = (179.07692307692307, 248.3653846153846)
  Hole 12: Area = 25, Centroid = (184.0, 44.0)
  Hole 13: Area = 

## Filled Bottles

In [83]:
!python python/main.py filled-bottles data/input/Bottles.tif

Found 5 bottle regions.
  Bottle 1: Centroid = (189.45814479638008, 254.422935520362)
  Bottle 2: Centroid = (185.72131329377183, 27.78731074260995)
  Bottle 3: Centroid = (190.09730435729057, 134.85520444073578)
  Bottle 4: Centroid = (190.1001378709818, 372.85349394093316)
  Bottle 5: Centroid = (190.20929206329194, 472.1192712601652)
Region 1 corners: (16, 340, 206, 304)
Colour levels: [[ 0. 12. 87.]
 [ 8. 23. 68.]
 [28. 12. 59.]
 [38.  9. 52.]
 [43.  8. 48.]
 [47.  7. 45.]
 [51.  5. 43.]
 [51.  5. 43.]
 [53.  3. 43.]
 [53.  3. 43.]
 [53.  3. 43.]
 [53.  3. 43.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  3. 43.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  4. 42.]
 [53.  5. 41.]
 [53.  5. 41.]
 [53.  5. 41.]
 [53.  5. 41.]
 [52.  6. 41.]
 [53.  5. 41.]
 [53.  5. 41.]
 [49.  8. 42.]
 [47.  6. 46.]
 [45.  5. 49.]
 [44.  6. 49.]
 [44.  4. 51.]
 [43.  5. 51.]
 [43.  5. 51.]
 [43.  5. 51.]
 [44.  4. 51.]
 [44.  4. 51.]
 [44.  4. 51.]
 [44.  4